### ISSUE TITLE
Scanner times out after sometime

### ISSUE THREAD

**Issue by DeltaCream** [AlvaroParker/libfprint-rs#4]
We are creating a fingerprint scanner for a client.
One of the things we noticed was that after opening the fingerprint scanner for some time without input, it automatically prints an error message and exits the application. 
`Fingerprint could not be identified due to an error: Error { domain: fp - device - error - quark, code: 257, message: "Device disabled to prevent overheating." }`
Is there a way to disable this or prevent the scanner from timing out?

**Comment by AlvaroParker** [comment]
This error is related to the underlying `libfprint` C library. See [libfprint](https://gitlab.freedesktop.org/libfprint/libfprint) for more details
